---
title: "phyloseq_H5_Heatmap Plots"
author: "wentao"
date: "2019/8/23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 热图展示OTU及其丰度信息
## 简介
### 具有生态结构的热图
在2010年Rajaram and Oono在BMC Genomics期刊上就描述了如何使用排序的方法来组织热图行列排序。
而不是使用层次聚类（hierarchical、cluster analysis）。在许多情况下基于排序的聚类比h-clustering更有用。这篇文章作者提供了许多案例，并打包放在了了R包NeatMap。NeatMap包可以直接使用基于测序得到的物种丰度otu表格，但是其NMDS和PCA排序方法中共不支持基于生态学的排序。

二phyloseq集合了大量的生态学算法，所以我们希望填补这个空白。在phyloseq包中写如了函数plot_heatmap：一个基于生态学的NeatMap扩展，用于热图的生态学排序并使用ggplot展示具有生态学意义的热图。在plot_heatmap函数中包含的距离算法和排序方法和plot_ordination函数相同，以支持大量的激励和排序方法。
，具有强大的生态学意义。

plot_heatmap函数提供对x轴和y轴标签的重定义，支持作者自定义，作为快速解读生态学意义数据的一个尝试。注意本函数所做热图并没有在热图旁边叠加聚类树状图，因为者并不是基于层次聚类组织的x和y轴顺序。

### 热图颜色无需太热
传统意义上来讲，热图颜色基本为一个暖色和一个冷色，其实在使用OTU表格作为输入，由于大量的OTU具有低丰度，而我们一般关注少数高丰度OTU的丰度变化。所以，就这一点而言我们的热土冷/热之间的阈值在于是否具有实际意义的OTU。plot_heatmap将丰度确缺失的OTU，默认定义黑色，或者自定义颜色，不纳入颜色变化梯度中。


```{R}
library("phyloseq"); packageVersion("phyloseq")
library("ggplot2"); packageVersion("ggplot2")
theme_set(theme_bw())
```

### 展示一个具有300个门类的数据热图
**Plot a 300-taxa dataset**

下面这两行代码将提取丰度最高的前300个门类（在做这一步的时候数据没有进行任何前处理，这里也不推荐）
><font size=2>The following two lines subset the dataset to just the top 300 most abundant Bacteria taxa across all samples (in this case, with no prior preprocessing. Not recommended, but quick).


```{R}
data("GlobalPatterns")
gpt <- subset_taxa(GlobalPatterns, Kingdom=="Bacteria")
gpt <- prune_taxa(names(sort(taxa_sums(gpt),TRUE)[1:300]), gpt)
plot_heatmap(gpt, sample.label="SampleType")
```

### 根据古菌门水平物种分类提取更小的数据集
**Subset a smaller dataset based on an Archaeal phylum**

#### subset_taxa函数提取Crenarchaeota门的OTU后展示丰度
plot_heatmap函数默认x轴为样品名，y轴为otu名。

```{R}
gpac <- subset_taxa(GlobalPatterns, Phylum=="Crenarchaeota")
#默认热图展示
plot_heatmap(gpac)
```

### 设置距离参数和排序方法对想轴和y轴项目排序做一个调整
**Re-label by a sample variable and taxonomic family**

这里基于bray距离使用NMDS对坐标进行排序。门类使用科水平展示。


><font size=2>Here is an example re-labelling based on the “SampleType” sample variable and the taxonomic rank of “Family”.

```{R}

(p <- plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family"))
```
### 基于list的图形修改模式修改xy坐标轴标签
**Re-label axis titles**

通过list形式对图形横纵坐标轴标签做一个修改。

><font size=2>What if you wanted to change the axis labels, but not the labels on individual features?

```{R}
p$scales$scales[[1]]$name <- "My X-Axis"
p$scales$scales[[2]]$name <- "My Y-Axis"
print(p)
```
### 现在重新出图，但是改变颜色映射
**Now repeat the plot, but change the color scheme.**

low和high参数设置颜色区间，改变颜色是有价值的，根据你文章中图形的基调进行修改时重要的。

><font size=2>Changing the color scheme might be worthwhile, depending on the graphics device or paper on which you want to display the heatmap.

```{R}
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#000033", high="#CCFF66")
```

更改为红色系

><font size=2>Here is a dark-blue to red scheme.

```{R}
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#000033", high="#FF3300")
```
换个颜色，再次更改：

```{R}
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#000033", high="#66CCFF")
```

na.value="white"设置丰度为0的区域为白色,这里修改后阅读性更强。

><font size=2>Here is a “dark on light” color scheme. Note that we change the background value (the value of the NA and 0 elements)

```{R}
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#66CCFF", high="#000033", na.value="white")
```
### 更换距离做NMDS排序
**Now try different ordination methods, distances**

现在尝试默认的配色方案，但是我们使用不同的生态学距离和排序方法。

><font size=2>Now try the default color scheme, but using different ecological distances/ordinations. For example, NMDS ordination on the jaccard distance.

```{R}
plot_heatmap(gpac, "NMDS", "jaccard")
```
#### DCA
```{R}
plot_heatmap(gpac, "DCA", "none", "SampleType", "Family")
```
#### RDA
```{R}
plot_heatmap(gpac, "RDA", "none", "SampleType", "Family")
```
#### PCoA
```{R}
plot_heatmap(gpac, "PCoA", "bray", "SampleType", "Family")
```
#### unifrac距离的PCOA
```{R}
plot_heatmap(gpac, "PCoA", "unifrac", "SampleType", "Family")
```

```{R}
plot_heatmap(gpac, "MDS", "unifrac", "SampleType", "Family", weighted=TRUE)
```

### 以下是使用base-R热图的方法，以防您想要与plot_heatmap进行比较。
作者认为这些聚类存在问题。大家如果有兴趣可以点击源地址进行了解。

><font size=2>Here is how you might create a heatmap using base-R graphics and the more common (but problematic) hierarchical clustering organization, in case you want to compare with plot_heatmap, for example.
```{R}
# ?heatmap
heatmap(otu_table(gpac))
```

### reference
https://joey711.github.io/phyloseq/plot_heatmap-examples.html
